// GrainData.js
export const grainsData = [
    {
      id: 1,
      name: "Quinoa",
      imageUrl: "https://media.istockphoto.com/id/815162944/photo/quinoa-seeds.jpg?s=1024x1024&w=is&k=20&c=cjf2HaE4rOX5xwQ9KqVGd_bP181XgU4WHCVFJ6pa5QI=",
      ingredients: ["Quinoa"],
      nutrition: {
        calories: 120,
        protein: "4g",
        fat: "2g",
        carbs: "21g",
      },
      price: "$5.99",
    },
    {
      id: 2,
      name: "Brown Rice",
      imageUrl: "https://images.pexels.com/photos/4110253/pexels-photo-4110253.jpeg?auto=compress&cs=tinysrgb&w=600",
      ingredients: ["Brown Rice"],
      nutrition: {
        calories: 150,
        protein: "3g",
        fat: "1g",
        carbs: "32g",
      },
      price: "$3.49",
    },
    {
      id: 3,
      name: "Oats",
      imageUrl: "https://images.pexels.com/photos/8108192/pexels-photo-8108192.jpeg?auto=compress&cs=tinysrgb&w=600",
      ingredients: ["Oats"],
      nutrition: {
        calories: 140,
        protein: "5g",
        fat: "2.5g",
        carbs: "27g",
      },
      price: "$4.25",
    },
    {
      id: 4,
      name: "Barley",
      imageUrl: "https://images.pexels.com/photos/326082/pexels-photo-326082.jpeg?auto=compress&cs=tinysrgb&w=600",
      ingredients: ["Barley"],
      nutrition: {
        calories: 150,
        protein: "3.5g",
        fat: "0.5g",
        carbs: "32g",
      },
      price: "$2.99",
    },
    {
      id: 5,
      name: "Millet",
      imageUrl: "https://static.vecteezy.com/system/resources/previews/002/859/494/non_2x/close-up-of-pearl-millet-bajra-with-wooden-spoon-photo.jpg",
      ingredients: ["Millet"],
      nutrition: {
        calories: 207,
        protein: "6g",
        fat: "1.2g",
        carbs: "41g",
      },
      price: "$3.89",
    },
    {
      id: 6,
      name: "Farro",
      imageUrl: "https://media.istockphoto.com/id/497746164/photo/whole-unpolished-spelt-in-a-with-a-spoon.jpg?s=612x612&w=0&k=20&c=IR9KyvwT3FVDV78nxwp4DHrH4Z8hwOfzIIaY1XOyX_I=",
      ingredients: ["Farro"],
      nutrition: {
        calories: 170,
        protein: "7g",
        fat: "1g",
        carbs: "34g",
      },
      price: "$4.99",
    },
    {
      id: 7,
      name: "Rye",
      imageUrl: "https://media.istockphoto.com/id/489078546/photo/harvest.jpg?s=612x612&w=0&k=20&c=8TrkNk0c2zSSMFuUJHVK7L4yWWZIQPvr3V5XI2BY-Fs=",
      ingredients: ["Rye"],
      nutrition: {
        calories: 100,
        protein: "3g",
        fat: "1g",
        carbs: "21g",
      },
      price: "$3.79",
    },
    {
      id: 8,
      name: "Buckwheat",
      imageUrl: "https://media.istockphoto.com/id/114332953/photo/wooden-spoon-filled-with-buckwheat-grain.jpg?s=612x612&w=0&k=20&c=KfXy1vGT39nYOsubPGFzsjkj4eT1auOfHdoYD47GXjg=",
      ingredients: ["Buckwheat"],
      nutrition: {
        calories: 155,
        protein: "6g",
        fat: "1g",
        carbs: "33g",
      },
      price: "$3.29",
    },
    {
      id: 9,
      name: "Sorghum",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdoYP4VzN8QnOxfuHBi06k14C1zjqj2X1ln0b1fgUODw6fTi6IzVJpiMsvTdRUT5ThJI4&usqp=CAU",
      ingredients: ["Sorghum"],
      nutrition: {
        calories: 150,
        protein: "5g",
        fat: "1.5g",
        carbs: "33g",
      },
      price: "$4.49",
    },
    {
      id: 10,
      name: "Teff",
      imageUrl: "https://www.shutterstock.com/image-photo/pile-uncooked-teff-grain-spoon-260nw-671442076.jpg",
      ingredients: ["Teff"],
      nutrition: {
        calories: 250,
        protein: "10g",
        fat: "2g",
        carbs: "50g",
      },
      price: "$5.49",
    },
    {
      id: 11,
      name: "Spelt",
      imageUrl: "https://media.gettyimages.com/id/615835094/photo/raw-spelt-flour-pasta-bread.jpg?s=612x612&w=gi&k=20&c=86G-yZFx2dT-bNcBEpSzpsLviyJlU4UOdhBM4VrwtBA=",
      ingredients: ["Spelt"],
      nutrition: {
        calories: 220,
        protein: "10g",
        fat: "2g",
        carbs: "45g",
      },
      price: "$4.75",
    },
    {
      id: 12,
      name: "Cornmeal",
      imageUrl: "https://media.istockphoto.com/id/1395535034/photo/cornmeal-polenta.jpg?s=612x612&w=0&k=20&c=4H-BbE1ioeduEOo32AK_UkpJnuvNx2AzazGbbRGKXMo=",
      ingredients: ["Corn"],
      nutrition: {
        calories: 120,
        protein: "3g",
        fat: "1g",
        carbs: "25g",
      },
      price: "$2.50",
    },
    {
      id: 13,
      name: "Wild Rice",
      imageUrl: "https://c8.alamy.com/comp/DPD1XH/wild-rice-and-brown-rice-DPD1XH.jpg",
      ingredients: ["Wild Rice"],
      nutrition: {
        calories: 160,
        protein: "6g",
        fat: "1g",
        carbs: "33g",
      },
      price: "$6.99",
    },
    {
      id: 14,
      name: "Black Rice",
      imageUrl: "https://media.gettyimages.com/id/1475232928/photo/black-rice-in-bowl.jpg?s=612x612&w=gi&k=20&c=ph6eNQufMKeY5Vn6XPGbB_6GhxZH48WQwpdkktzKXO8=",
      ingredients: ["Black Rice"],
      nutrition: {
        calories: 200,
        protein: "8g",
        fat: "1.5g",
        carbs: "42g",
      },
      price: "$5.25",
    },
    {
      id: 15,
      name: "White Rice",
      imageUrl: "https://media.gettyimages.com/id/155156716/photo/rice.jpg?s=612x612&w=gi&k=20&c=mzJ8qWgsO-xQKNt6H5zrqRQ_9JzA4JEXmZZUkAuXstI=",
      ingredients: ["White Rice"],
      nutrition: {
        calories: 130,
        protein: "2g",
        fat: "0.5g",
        carbs: "28g",
      },
      price: "$2.99",
    },
    {
      id: 16,
      name: "Puffed Rice",
      imageUrl: "https://t4.ftcdn.net/jpg/05/35/69/31/360_F_535693104_bO6cUikQ9ZKZi4BwqeadI5assFNChRoz.jpg",
      ingredients: ["Puffed Rice"],
      nutrition: {
        calories: 100,
        protein: "2g",
        fat: "0g",
        carbs: "24g",
      },
      price: "$1.99",
    },
    {
      id: 17,
      name: "Brown Basmati Rice",
      imageUrl: "https://media.gettyimages.com/id/175586192/photo/basmati-rice.jpg?s=612x612&w=gi&k=20&c=6N2ayHEmIULGjR2lzAYJ2fM1YpfUqklrBGZBXa0AO1A=",
      ingredients: ["Brown Basmati Rice"],
      nutrition: {
        calories: 150,
        protein: "4g",
        fat: "1g",
        carbs: "32g",
      },
      price: "$4.29",
    },
    {
      id: 18,
      name: "Jasmine Rice",
      imageUrl: "https://static.vecteezy.com/system/resources/thumbnails/003/115/104/small_2x/asian-rice-in-wooden-spoon-free-photo.jpg",
      ingredients: ["Jasmine Rice"],
      nutrition: {
        calories: 160,
        protein: "4g",
        fat: "1g",
        carbs: "36g",
      },
      price: "$3.99",
    },
    {
      id: 19,
      name: "Freekeh",
      imageUrl: "https://media.istockphoto.com/id/1500336347/photo/raw-freekeh-or-firik-in-ceramic-bowl-with-spoon-on-burlap-on-wooden-background-concept-of.jpg?s=612x612&w=0&k=20&c=4O85iebDC2nTsG8FGHqq7C5tyK_qtHEXOWXROSPBTyM=",
      ingredients: ["Freekeh"],
      nutrition: {
        calories: 130,
        protein: "5g",
        fat: "1g",
        carbs: "28g",
      },
      price: "$5.75",
    },
  ];
  
  